kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    app.openshift.io/vcs-uri: >-
      https://github.com/rh-soln-pattern-sentiment-analysis/sentiment-analysis-model.git
    deployment.kubernetes.io/revision: '3'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"senti2:latest","namespace":"test"},"fieldPath":"spec.template.spec.containers[?(@.name==\"senti2\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  name: senti2
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: senti2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: senti2
        deploymentconfig: senti2
    spec:
      containers:
        - name: senti2
          image: >-
            image-registry.openshift-image-registry.svc:5000/test/senti2@sha256:fd2aec11cc0239b99a05266b451ca9f6e7858877014c84cdf7e3fb206053ef52
          envFrom:
            - configMapRef:
                name: sentiment
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600